### ISSUE TITLE
[GalacticSearch] have robot move until power cell is detected from vision

### ISSUE THREAD

**Issue by Ryan4545** [cavineers/RobotCode2021#63]
If no powercell is detected from vision have the robot spin until a powercell is being retrieved from vision.

**Comment by topmastered** [comment]
What's the reason behind doing this?

**Comment by Ryan4545** [comment]
Because if we doing real time updates to the plotting, the field will not always be in view necessarily, so if no powercells are in view we have to move the bot so the vision can find where the next one is.
Once 3 powercells have been picked up, we can they find the shooting target and fire away.

**Comment by topmastered** [comment]
For galactic search, the robot will always be facing the direction of all 3 power cells, and this is the reason we have a 180deg cam.
Second, the galactic search doesn't actually shoot, just needs to cross the end plane.

**Comment by Ryan4545** [comment]
Yeah, but we will have to turn and such to get a better angle to pick up the powercells, no?

**Comment by Ryan4545** [comment]
And the target and shoot was more for an example of doing something after we know all three have been picked up.

**Comment by topmastered** [comment]
The robot doesn't need to rotate. It will start backwards, intake facing the balls and end-zone. It should then calculate the reverse X, Y coordinates for the robot to only use strafe and reverse to achieve. It doesn't need rotation to pick the power cells up and can navigate to them based purely on the X distance and Y distance.

**Comment by Ryan4545** [comment]
So the path does not have to dynamic then? The path can be set automatically at the start of the challenge and then vision, after the initial plotting, becomes obsolete.

**Comment by topmastered** [comment]
No, the vision should be continuous. The vision should act as closed-loop feedback throughout the whole command. You can even use your own X, Y PID to directly feed into the swerve method, without having to do position plotting.
That method would be more precise but adds a little complexity, overall a decent option.

 I'm just saying, you don't need a passive rotation when there is no target ball. It would also waste time, and it could become a safety thing if it turns 180deg and finds a couple of balls behind it. Also, it should never run into the scenario it can't find anything because of the 180 FOV.
